backend/_facemash_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('api/', include('apps.api.urls')),
	path('', include('frontend.urls')),  # Маршруты из test_app без префикса
]

if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/frontend/urls.py
from django.urls import path
from frontend.views.matchups.views import MatchupView
from frontend.views.competitors.views import CompetitorView
from frontend.views.ratings.views import RatingView
from frontend.views.tournaments.views import TournamentView, WinnerTournamentView, StageTournamentView, HomeTournamentView, CreateTournamentView, MatchupTournamentView
from frontend.views.profiles.views import ProfileView, RegisterView, LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', MatchupView.as_view(), name='home'),  # Пример маршрута
	
	path('tournament/', HomeTournamentView.as_view(), name='tournament-home'),
	path('tournament/<int:tournament_id>/<int:round_number>/matchup/', MatchupTournamentView.as_view(), name='tournament-matchup-actual'),
	path('tournament/<int:tournament_id>/<int:round_number>/<int:matchup_number>/', MatchupTournamentView.as_view(), name='tournament-matchup'),
	path('tournament/<int:tournament_id>/<int:round_number>/', StageTournamentView.as_view(), name='tournament-stage'),
	path('tournament/<int:tournament_id>/', TournamentView.as_view(), name='tournament-info'),
	path('tournament/<int:tournament_id>/winner/', WinnerTournamentView.as_view(), name='tournament-winner'),
	path('tournament/create', CreateTournamentView.as_view(), name='tournament-create'),
	
	path('competitor/<int:competitor_id>/', CompetitorView.as_view(), name='competitor'),
	path('rating/', RatingView.as_view(), name='rating'),
	path('profile/', ProfileView.as_view(), name='profile'),
	path('register/', RegisterView.as_view(), name='register'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
]

backend/apps/tournaments/forms.py
from django import forms
from apps.competitors.models import Location

class TournamentSelectionForm(forms.Form):
	cities = forms.ModelMultipleChoiceField(
		queryset=Location.objects.all(),
		widget=forms.CheckboxSelectMultiple,
		label="Выберите города",
		required = True,
		error_messages={
			'required': "Пожалуйста, выберите хотя бы один город.",  # Изменяем текст ошибки
		}
	)

	# Поля для ввода данных
	num_participants = forms.CharField(
		label="Участников",
		required=True,
		widget=forms.NumberInput(attrs={
			"readonly": "readonly",
			'placeholder': 'Не редактируется'
			}),
		error_messages={'required': "Укажите количество участников."}
	)
	num_rounds = forms.CharField(
		label="Раундов",
		required=True,
		error_messages={'required': "Укажите количество раундов."}
	)
	num_per_matchup = forms.CharField(
		label="В одном матчапе",
		required=True,
		error_messages={'required': "Укажите количество участников в одном матчапе."}
	)

backend/frontend/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.utils.safestring import mark_safe
from django.core.serializers import serialize
from services.competitors_service import LocalCompetitorService
from services.ratings_service import LocalRatingService, APIRatingService
from frontend.helpers import GetData
from frontend.handlers import MatchupHandler
import json


class HomeView(View):

	def get(self, request):
		winner_id = request.session.get("winner_id")
		winner_position = request.session.get("winner_position")
		winner_image_index = request.session.get("winner_image_index")
		
		home_helper = GetData()
		if winner_id:
			data = home_helper.get_enemy(winner_id, winner_position, winner_image_index)
		else:
			data = home_helper.get_data_competitors(2)
		
		ratings = LocalRatingService.get_top_rating()
		
		return render(
			request, 
			'frontend/indexhtml.html',
			{
				'data': data,
				'ratings': ratings,
			}
		)
	
	def post(self, request):
		winner_id = request.POST.get("winner_id")
		loser_id = request.POST.get("loser_id")
		print(f"WINNER{winner_id}, {loser_id}")
		winner_position = request.POST.get("winner_position")
		winner_image_index = request.POST.get("winner_image_index")
		
		matchup_handler = MatchupHandler(winner_id, loser_id)
		matchup_handler.process_matchup()

		request.session['winner_id'] = winner_id
		request.session['loser_id'] = loser_id
		request.session['winner_position'] = winner_position
		request.session['winner_image_index'] = winner_image_index

		return redirect("home-archieve")


class HomeViewJS(View):

	home_helper = GetData()

	def get(self, request):
		winner_id = request.session.get("winner_id")
		winner_position = request.session.get("winner_position")
		winner_image_index = request.session.get("winner_image_index")
		
		
		if winner_id:
			data = self.home_helper.get_enemy(winner_id, winner_position, winner_image_index)
		else:
			data = self.home_helper.get_data_competitors(2)
		
		ratings = LocalRatingService.get_top_rating()
		
		return render(
			request, 
			'frontend/index.html',
			{
				'data': data,
				'ratings': ratings,
			}
		)
	
	def post(self, request):
		print('я тут')
		if request.headers.get('x-requested-with') == 'XMLHttpRequest':
			winner_id = request.POST.get("winner_id")
			loser_id = request.POST.get("loser_id")
			print(f"WINNER{winner_id}, {loser_id}")
			winner_position = request.POST.get("winner_position")
			winner_image_index = request.POST.get("winner_image_index")
			
			matchup_handler = MatchupHandler(winner_id, loser_id)
			matchup_handler.process_matchup()
			
			new_loser = self.home_helper.get_competitor_js(
				winner_id,
				loser_id,
				winner_position
			)
			print(new_loser)
			winner_rating = self.home_helper.get_winner_rating(winner_id)
			top_ratings = APIRatingService.get_top_rating()
			
			request.session['winner_id'] = winner_id
			request.session['loser_id'] = loser_id
			request.session['winner_position'] = winner_position
			request.session['winner_image_index'] = winner_image_index
			return JsonResponse({
				"status": "success",
				"loser_data": new_loser,
				"winner_rating": winner_rating,
				"top_ratings": top_ratings
			})
		

class ProfileView(View):

	home_helper = GetData()

	def get(self, request, profile_id: int):
		data = self.home_helper.get_competitor_profile(profile_id)
		return render(
			request, 
			'frontend/profile.html', 
			{'data': data}
		)

backend/frontend/views/competitor.py
from django.shortcuts import render
from django.views import View
from frontend.helpers import GetData


class CompetitorView(View):

	home_helper = GetData()

	def get(self, request, competitor_id: int):
		data = self.home_helper.get_competitor_profile(competitor_id)
		return render(
			request, 
			'frontend/competitor.html', 
			{'data': data}
		)
	

backend/frontend/views/competitors/views.py
from django.shortcuts import render
from django.views import View
from services.competitors.data_service import CompetitorGetData
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.core.paginator import Paginator


class CompetitorView(LoginRequiredMixin, TemplateView):

	data_service = CompetitorGetData()

	def get(self, request, competitor_id: int):
		data = self.data_service.get_competitor_profile(competitor_id)
		matchups = data["matchups"]
		paginator = Paginator(matchups, 10)
		page_number = request.GET.get('page', 1)
		page_obj = paginator.get_page(page_number)
		return render(
			request, 
			'frontend/competitors/competitor.html', 
			{
				'data': data,
				'page_obj': page_obj,
			}
		)
	

backend/frontend/views/matchup.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from services.ratings_service import LocalRatingService, APIRatingService
from frontend.helpers import GetData
from frontend.handlers import MatchupHandler


class HomeView(View):

	def get(self, request):
		winner_id = request.session.get("winner_id")
		winner_position = request.session.get("winner_position")
		winner_image_index = request.session.get("winner_image_index")
		
		home_helper = GetData()
		if winner_id:
			data = home_helper.get_enemy(winner_id, winner_position, winner_image_index)
		else:
			data = home_helper.get_data_competitors(2)
		
		ratings = LocalRatingService.get_top_rating()
		
		return render(
			request, 
			'frontend/indexhtml.html',
			{
				'data': data,
				'ratings': ratings,
			}
		)
	
	def post(self, request):
		winner_id = request.POST.get("winner_id")
		loser_id = request.POST.get("loser_id")
		print(f"WINNER{winner_id}, {loser_id}")
		winner_position = request.POST.get("winner_position")
		winner_image_index = request.POST.get("winner_image_index")
		
		matchup_handler = MatchupHandler(winner_id, loser_id)
		matchup_handler.process_matchup()

		request.session['winner_id'] = winner_id
		request.session['loser_id'] = loser_id
		request.session['winner_position'] = winner_position
		request.session['winner_image_index'] = winner_image_index

		return redirect("home-archieve")


class HomeViewJS(View):

	home_helper = GetData()

	def get(self, request):
		winner_id = request.session.get("winner_id")
		winner_position = request.session.get("winner_position")
		winner_image_index = request.session.get("winner_image_index")
		
		
		if winner_id:
			data = self.home_helper.get_enemy(winner_id, winner_position, winner_image_index)
		else:
			data = self.home_helper.get_data_competitors(2)
		
		ratings = LocalRatingService.get_top_rating()
		
		return render(
			request, 
			'frontend/matchup.html',
			{
				'data': data,
				'ratings': ratings,
			}
		)
	
	def post(self, request):
		print('я тут')
		if request.headers.get('x-requested-with') == 'XMLHttpRequest':
			winner_id = request.POST.get("winner_id")
			loser_id = request.POST.get("loser_id")
			print(f"WINNER{winner_id}, {loser_id}")
			winner_position = request.POST.get("winner_position")
			winner_image_index = request.POST.get("winner_image_index")
			
			matchup_handler = MatchupHandler(winner_id, loser_id)
			matchup_handler.process_matchup()
			
			new_loser = self.home_helper.get_competitor_js(
				winner_id,
				loser_id,
				winner_position
			)
			print(new_loser)
			winner_rating = self.home_helper.get_winner_rating(winner_id)
			top_ratings = APIRatingService.get_top_rating()
			
			request.session['winner_id'] = winner_id
			request.session['loser_id'] = loser_id
			request.session['winner_position'] = winner_position
			request.session['winner_image_index'] = winner_image_index
			return JsonResponse({
				"status": "success",
				"loser_data": new_loser,
				"winner_rating": winner_rating,
				"top_ratings": top_ratings
			})

backend/frontend/views/matchups/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from services.ratings.service import LocalRatingService, APIRatingService
from services.matchups.helper import MatchupHelper, SavedMatchupHelper
from services.matchups.data_service import MatchupGetData, MatchupGetDataJS
from services.matchups.handler import MatchupHandler


class MatchupView(View):

	matchup_helper_service = MatchupHelper()
	saved_matchup_helper_service = SavedMatchupHelper()
	data_service = MatchupGetData()
	data_service_js = MatchupGetDataJS()

	def get(self, request):
		
		if request.user.is_authenticated:
			mode = request.GET.get('mode')
			if mode == 'refresh':
				competitor_1, competitor_2 = self.matchup_helper_service.get_two_competitors()
				updated_matchup = self.saved_matchup_helper_service.update_saved_matchup(
					request.user,
					competitor_1.id,
					'1',
					0,
					competitor_2.id
				)
				data = self.data_service.data_matchup(
						competitor_1_id=updated_matchup.competitor_1,
						competitor_2_id=updated_matchup.competitor_2,
						competitor_1_index=updated_matchup.competitor_1_ii,
						competitor_2_index=updated_matchup.competitor_2_ii,
					)
				return redirect('home')
			else:
				saved_matchup = self.saved_matchup_helper_service.get_saved_matchup(request)
				if saved_matchup:
					data = self.data_service.data_matchup(
						competitor_1_id=saved_matchup.competitor_1,
						competitor_2_id=saved_matchup.competitor_2,
						competitor_1_index=saved_matchup.competitor_1_ii,
						competitor_2_index=saved_matchup.competitor_2_ii,
					)
		else:
			
			winner_id = request.session.get("winner_id")
			winner_position = request.session.get("winner_position")
			winner_image_index = request.session.get("winner_image_index")
			enemy_id = request.session.get("enemy_id")
			enemy_1 = request.session.get("enemy_1")
			enemy_2 = request.session.get("enemy_2")

			if enemy_1 and enemy_2:
				data = self.data_service.data_matchup(
					competitor_1_id=enemy_1, 
					competitor_2_id=enemy_2
				)
			elif enemy_id:
				data = self.data_service.data_matchup(
					competitor_1_id=winner_id,
					competitor_2_id=enemy_id,
					competitor_1_index=winner_image_index,
					competitor_1_position=winner_position
				)
			else:
				data = self.data_service.data_matchup(competitors=2)
				for i, competitor in enumerate(data):
					request.session[f'enemy_{i+1}'] = data[competitor]['id']
			if not enemy_id:
				for competitor in data:
					if winner_id:
						if int(winner_id) != data[competitor]['id']:
							request.session['enemy_id'] = data[competitor]['id']

		ratings = LocalRatingService.get_top_rating(20)
		
		return render(
			request, 
			'frontend/matchups/matchup.html',
			{
				'data': data,
				'ratings': ratings,
			}
		)
	
	def post(self, request):
		if request.headers.get('x-requested-with') == 'XMLHttpRequest':
			winner_id = request.POST.get("winner_id")
			loser_id = request.POST.get("loser_id")
			winner_position = request.POST.get("winner_position")
			winner_image_index = request.POST.get("winner_image_index")
			
			matchup_handler = MatchupHandler(request, winner_id, loser_id)
			matchup_handler.process_matchup()
			
			new_enemy = self.data_service_js.get_data_competitor_js(
				winner_id,
				loser_id,
				winner_position
			)

			for competitor in new_enemy:
				if int(winner_id) != new_enemy[competitor]["competitor"]['id']:
					enemy_id = new_enemy[competitor]['competitor']['id']
					if request.user.is_authenticated:
						self.saved_matchup_helper_service.update_saved_matchup(
							profile_id=request.user,
							winner_id=winner_id,
							winner_position=winner_position,
							winner_image_index=winner_image_index,
							enemy_id=enemy_id
						)
					else:
						request.session['enemy_id'] = enemy_id
			
			winner_rating = self.matchup_helper_service.get_winner_rating(winner_id)
			top_ratings = APIRatingService.get_top_rating(20)
			
			if not request.user.is_authenticated:
				request.session['winner_id'] = winner_id
				request.session['winner_position'] = winner_position
				request.session['winner_image_index'] = winner_image_index
				request.session['enemy_1'] = None
				request.session['enemy_2'] = None
			return JsonResponse({
				"status": "success",
				"loser_data": new_enemy,
				"winner_rating": winner_rating,
				"top_ratings": top_ratings
			})

backend/frontend/views/profile.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.views import View
from profiles.forms import RegistrationForm
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm


class ProfileView(View):

	def get(self, request):
		return render(request, 'frontend/profile.html')

class RegisterView(FormView):
	template_name = 'frontend/register.html'
	form_class = RegistrationForm
	success_url = reverse_lazy('home')

	def form_valid(self, form):
		# Создаем пользователя
		user = form.save(commit=False)
		user.set_password(form.cleaned_data['password'])
		user.save()
		# Вход пользователя в систему
		login(self.request, user)
		# Редирект на success_url
		return redirect(self.success_url)

	def form_invalid(self, form):
		# Отображение ошибок, если форма не валидна
		return self.render_to_response(self.get_context_data(form=form))
	
class LoginView(LoginView):
	template_name = 'frontend/login.html'
	authentication_form = AuthenticationForm
	success_url = reverse_lazy('profile')

	def get_success_url(self):
		# Используем success_url для перенаправления после успешного входа
		return self.success_url

	def form_invalid(self, form):
		form.errors.clear()
		# Добавляем кастомное сообщение об ошибке
		form.add_error(None, "Неверное имя пользователя или пароль. Попробуйте снова.")
		return self.render_to_response(self.get_context_data(form=form))

backend/frontend/templates/frontend/tournaments/create.html
{% extends 'base.html' %}
{% load static %}
{% block css%}
<link rel="stylesheet" href="{% static 'css/base_tournament.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/tournaments/create.css' %}">
{% endblock %}
{% block title %}
Создать турнир
{% endblock %}


{% block content %}
<form method="POST" class="send-cities" action="{% url 'tournament-create' %}">
	<div class="wrapper-create">
		<div class="selected-section">
			<h1>Страница создания турнира</h1>
			{% csrf_token %}

			{% if tournament_form.errors %}
				<div class="errorlist">
					<strong>Ошибки:</strong>
					<ul>
						{% for field, errors in tournament_form.errors.items %}
							{% for error in errors %}
								<li>{{ error }}</li>  <!-- Выводим только текст ошибки -->
							{% endfor %}
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			
			<label class="selection-label">Выберите элементы</label>
			
			<div class="checkbox-container">
				{% for checkbox in tournament_form.cities %}
					<div class="checkbox-item">
						{{ checkbox }}
					</div>
				{% endfor %}
			</div>
			<div class="button">
				<button type="submit">Начать игру</button>
			</div>
		</div>
		<div class="settings-section">
			<h1>Параметры</h1>
			<p id="user-count-display">Выбрано пользователей: 0</p>
			<br>
			<label for="id_num_rounds">{{ tournament_form.num_rounds.label }}</label> {{ tournament_form.num_rounds }}</p>
			<br>
			<label for="id_num_per_matchup">{{ tournament_form.num_per_matchup.label }}</label> {{ tournament_form.num_per_matchup }}</p>
			<br>
			<label for="id_num_participants" >{{ tournament_form.num_participants.label }} {{ tournament_form.num_participants}}</p>
			<br>
		</div>
	</div>
</form>


{% endblock %}

{% block scripts%}
	<script src="{% static 'frontend/js/tournament-create.js' %}" type="module" defer></script>
	<script src="{% static 'frontend/js/tournament-update.js' %}" type="module" defer></script>
{% endblock %}

backend/frontend/templates/frontend/tournaments/info.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base_tournament.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/tournaments/info.css' %}">
{% endblock %}
{% block title%}
Tournament Info Page
{% endblock %}


{% block content%}
<main>
	<div class="wrapper-tournament-info">
		<div class="list-info">
			<div class="tournament-competitors-info">
				<h1>Участники</h1>
			</div>
			<div class="table-info">
			<table>
				<thead>
					<tr>
						<th>Место</th>
						<th class="th-name">Имя</th>
						<th>Возраст</th>
						<th>Город</th>
						<th>Рейтинг</th>
						<th>Дельта</th>
					</tr>
				</thead>
				<tbody>
					{% for competitor, competitor_data in competitors_page%}
					<tr class="competitor-row" >
						<td>{% if competitor_data.tournament_info.final_position %}{{ competitor_data.tournament_info.final_position }}{% endif %}</td>
						<td class="competitor-name" data-competitor-id="{{ competitor_data.competitor_info.id }}">{{ competitor_data.competitor_info.name }}</td>
						<td>{% if competitor_data.competitor_info.age %}{{ competitor_data.competitor_info.age }}{% else %}-{% endif %}</td>
						<td class="competitor-city">{{ competitor_data.competitor_info.city }}</td>
						<td>{{ competitor_data.competitor_info.rating }}</td>
						<td>{{ competitor_data.tournament_info.delta_tournament }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			</div>
				<!-- Пагинация -->
			<div class="pagination">
			{% if competitors_page.has_previous %}
				<a href="?type={{ request.GET.type }}&page={{ competitors_page.previous_page_number }}"><</a>
			{% endif %}
				{% if competitors_page.number > 3 %}
					<a href="?type={{ request.GET.type }}&page=1">1</a>
					<span>...</span>
				{% elif competitors_page.number > 1 %}
					<a href="?type={{ request.GET.type }}&page=1">1</a>
				{% endif %}
				<!-- Динамический диапазон страниц -->
				{% for num in competitors_paginator.page_range %}
						{% if num > competitors_page.number|add:'-3' and num < competitors_page.number|add:'3' %}
							{% if num == competitors_page.number%}
								<span class="current"><strong>{{ num }}</strong></span> <!-- Текущая страница -->
							{% else %}
								{% if num != 1 %}
								<a href="?type={{ request.GET.type }}&page={{ num }}">{{ num }}</a>
							{% endif %}
						{% endif %}
					{% endif %}
				{% endfor %}

				<!-- Ссылка на последнюю страницу -->
				{% if competitors_page.number < competitors_paginator.num_pages|add:'-2' %}
					<span>...</span>
					<a href="?type={{ request.GET.type }}&page={{ competitors_paginator.num_pages }}">{{ competitors_paginator.num_pages }}</a>
				{% elif competitors_page.number|add:'2' < competitors_paginator.num_pages %}
					<a href="?type={{ request.GET.type }}&page={{ competitors_paginator.num_pages }}">{{ competitors_paginator.num_pages }}</a>
				{% endif %}

			{% if competitors_page.has_next %}
				<a href="?type={{ request.GET.type }}&page={{ competitors_page.next_page_number }}">></a>
			{% endif %}
			</div>
			{% if data.tournament_info.actual_round_number %}
				<div class="a-button">
					<a href='{% url 'tournament-matchup-actual' data.tournament_info.id data.tournament_info.actual_round_number%}'>Перейти к матчапам</a>
				</div>
			{% endif %}
		</div>
		<div class="round-stage-info">
			<div class="round-stage-head">
				<h1>История раундов</h1>
			</div>
			<div class="round-section">
			{% for round_number, round_data in data.rounds_info.items %}
				{% if not round_data.status == 'not started' %}
					{% if not round_data.status == 'completed' %}
						<p><a href="{% url 'tournament-stage' data.tournament_info.id round_number%}">Раунд {{round_number}} - текущий</a></p>
					{% else %}
						<p><a href="{% url 'tournament-stage' data.tournament_info.id round_number%}">Раунд {{round_number}} - закончен</a></p>
					{% endif %}
				{% endif %}
			{% endfor %}
			</div>
		</div>
		<div id="profile-detail">
			<div id="profile-photos"></div>
		</div>
	</div>
</main>
{% endblock %}
{% block scripts %}
<script> 
	const isAuth = {{ is_auth|yesno:"true,false" }}; 
</script>
<script src="{% static 'frontend/js/rating-competitor.js' %}" type="module" defer></script>
{% endblock %}

backend/frontend/templates/frontend/tournaments/main.html
{% extends 'base.html' %}
{% load static%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base_tournament.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/tournaments/main.css' %}">
{% endblock %}
{% block title%}
Турниры
{% endblock %}


{% block content%}
<div class="wrapper-tournament-main">
	
	<div class="tournaments-list">
		<div class="header-tournament">
			<h1>Активные турниры</h1>
		</div>
		<div class="tournament-progress">
		{% for tournament, value in data.in_progress_tournaments.items %}
			<p><a href="{% url 'tournament-stage' value.tournament_id value.actual_round %}">Турнир id#{{ value.tournament_id }}</a> {{value.status}}</p>
		{% endfor %}
		</div>
	</div>


	<div class="tournament-completed">
		<div class="header-tournament">
			<h1>Завершенные турниры</h1>
		</div>
		{% for tournament, value in data.completed_tournaments.items %}
			<p><a href="{% url 'tournament-info' value.tournament_id %}">Турнир id#{{ value.tournament_id }}</a> Победила: <a href="{% url 'competitor' value.winner_id.id %}">{{value.winner_id.name}}</a></p>
		{% endfor %}
	</div>

	<div class="to-button">
		<div class="a-button">
			<a href="{% url 'tournament-create'%}">Создать турнир</a>
		</div>
	</div>

</div>
{% endblock %}

backend/frontend/templates/frontend/tournaments/stage.html
{% extends 'base.html' %}
{% load static%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base_tournament.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/tournaments/stage.css' %}">
{% endblock %}
{% block title%}
Stage page
{% endblock %}


{% block content %}
<div class="wrapper-tournament-stage">
	<div class="stage-sidebar">
		
		<div class="table-info">
		<h1>Раунд номер {{stage_data.round_info.round_number}}</h1>
			<table>
				<tbody>
					{% for matchup, matchup_data in stage_data.matchups.items %}
					<tr class="competitor-row">
						<td><a class="matchup-link" href="{% url 'tournament-matchup' stage_data.tournament_info.id stage_data.round_info.round_number matchup %}">Матчап {{ matchup }} {{matchup_data.status}}</a></td>
						{% for competitor_number, competitor_data in matchup_data.competitors.items %}
						
							<td {% if competitor_data.round_info.result %}class="competitor-name matchup-winner"{% elif competitor_data.round_info.result == 0 %} class="competitor-name matchup-loser"{% else %}class="competitor-name"{% endif %} data-competitor-id="{{ competitor_data.competitor_info.id }}">
								{{ competitor_data.competitor_info.name }}
							</td>
						{% endfor %}
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		
		<div class="click-button">
			<div class="a-button">
			{% if not stage_data.tournament_info.winner_id %}
				<a href="{% url 'tournament-matchup-actual' stage_data.tournament_info.id stage_data.round_info.round_number %}">Перейти к матчапу</a>
			{% else %}
				<a href="{% url 'tournament-info' stage_data.tournament_info.id%}">В меню турнира</a>
			{% endif %}
			</div>
		</div>
		

	
	</div>
	<div id="profile-detail">
		<div id="profile-photos"></div>
	</div>
</div> 
{% endblock %} 
{% block scripts %}
<script> 
	const isAuth = {{ is_auth|yesno:"true,false" }}; 
</script>
<script src="{% static 'frontend/js/rating-competitor.js' %}" type="module" defer></script>
{% endblock %}